swagger: '2.0'
x-stoplight:
  id: 8h1qxm9s2vt21
info:
  title: txt2img
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  '/v1/images/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              image:
                $ref: '#/definitions/Image'
      operationId: get-image
    delete:
      summary: ''
      operationId: delete-image
      responses:
        '200':
          description: OK
  /v1/images:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: list-images
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              images:
                type: array
                items:
                  $ref: '#/definitions/Image'
    post:
      summary: ''
      operationId: create-image
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              image:
                $ref: '#/definitions/Image'
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              prompt:
                type: string
    parameters: []
definitions:
  Image:
    title: Image
    x-stoplight:
      id: 00fw3hzpujosv
    type: object
    properties:
      id:
        type: string
      prompt:
        type: string
      url:
        type: string

