# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.txt2img.v1 import txt2img_pb2 as protos_dot_txt2img_dot_v1_dot_txt2img__pb2


class Txt2ImgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateImage = channel.unary_unary(
                '/txt2img.v1.Txt2ImgService/GenerateImage',
                request_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GenerateImageResponse.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/txt2img.v1.Txt2ImgService/GetImage',
                request_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GetImageRequest.SerializeToString,
                response_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GetImageResponse.FromString,
                )
        self.ListImages = channel.unary_unary(
                '/txt2img.v1.Txt2ImgService/ListImages',
                request_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.ListImagesRequest.SerializeToString,
                response_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.ListImagesResponse.FromString,
                )
        self.DeleteImage = channel.unary_unary(
                '/txt2img.v1.Txt2ImgService/DeleteImage',
                request_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.DeleteImageRequest.SerializeToString,
                response_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.DeleteImageResponse.FromString,
                )


class Txt2ImgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Txt2ImgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GenerateImageRequest.FromString,
                    response_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GenerateImageResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GetImageRequest.FromString,
                    response_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GetImageResponse.SerializeToString,
            ),
            'ListImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListImages,
                    request_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.ListImagesRequest.FromString,
                    response_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.ListImagesResponse.SerializeToString,
            ),
            'DeleteImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteImage,
                    request_deserializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.DeleteImageRequest.FromString,
                    response_serializer=protos_dot_txt2img_dot_v1_dot_txt2img__pb2.DeleteImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'txt2img.v1.Txt2ImgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Txt2ImgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/txt2img.v1.Txt2ImgService/GenerateImage',
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GenerateImageRequest.SerializeToString,
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GenerateImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/txt2img.v1.Txt2ImgService/GetImage',
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GetImageRequest.SerializeToString,
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.GetImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/txt2img.v1.Txt2ImgService/ListImages',
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.ListImagesRequest.SerializeToString,
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.ListImagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/txt2img.v1.Txt2ImgService/DeleteImage',
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.DeleteImageRequest.SerializeToString,
            protos_dot_txt2img_dot_v1_dot_txt2img__pb2.DeleteImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
