# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/txt2img/v1/txt2img.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotos/txt2img/v1/txt2img.proto\x12\ntxt2img.v1\".\n\x14GenerateImageRequest\x12\x16\n\x06prompt\x18\x01 \x01(\tR\x06prompt\"\'\n\x15GenerateImageResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"!\n\x0fGetImageRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"$\n\x10GetImageResponse\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\"\x13\n\x11ListImagesRequest\",\n\x12ListImagesResponse\x12\x16\n\x06images\x18\x01 \x03(\tR\x06images\"$\n\x12\x44\x65leteImageRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x15\n\x13\x44\x65leteImageResponse2\xd2\x02\n\x0eTxt2ImgService\x12V\n\rGenerateImage\x12 .txt2img.v1.GenerateImageRequest\x1a!.txt2img.v1.GenerateImageResponse\"\x00\x12G\n\x08GetImage\x12\x1b.txt2img.v1.GetImageRequest\x1a\x1c.txt2img.v1.GetImageResponse\"\x00\x12M\n\nListImages\x12\x1d.txt2img.v1.ListImagesRequest\x1a\x1e.txt2img.v1.ListImagesResponse\"\x00\x12P\n\x0b\x44\x65leteImage\x12\x1e.txt2img.v1.DeleteImageRequest\x1a\x1f.txt2img.v1.DeleteImageResponse\"\x00\x42OZMgithub.com/eddiezane/open-source-summit-eu-2022-api-codegen/protos/txt2img/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.txt2img.v1.txt2img_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZMgithub.com/eddiezane/open-source-summit-eu-2022-api-codegen/protos/txt2img/v1'
  _GENERATEIMAGEREQUEST._serialized_start=47
  _GENERATEIMAGEREQUEST._serialized_end=93
  _GENERATEIMAGERESPONSE._serialized_start=95
  _GENERATEIMAGERESPONSE._serialized_end=134
  _GETIMAGEREQUEST._serialized_start=136
  _GETIMAGEREQUEST._serialized_end=169
  _GETIMAGERESPONSE._serialized_start=171
  _GETIMAGERESPONSE._serialized_end=207
  _LISTIMAGESREQUEST._serialized_start=209
  _LISTIMAGESREQUEST._serialized_end=228
  _LISTIMAGESRESPONSE._serialized_start=230
  _LISTIMAGESRESPONSE._serialized_end=274
  _DELETEIMAGEREQUEST._serialized_start=276
  _DELETEIMAGEREQUEST._serialized_end=312
  _DELETEIMAGERESPONSE._serialized_start=314
  _DELETEIMAGERESPONSE._serialized_end=335
  _TXT2IMGSERVICE._serialized_start=338
  _TXT2IMGSERVICE._serialized_end=676
# @@protoc_insertion_point(module_scope)
