# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: txt2img/v1/txt2img.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18txt2img/v1/txt2img.proto\x12\ntxt2img.v1\".\n\x14GenerateImageRequest\x12\x16\n\x06prompt\x18\x01 \x01(\tR\x06prompt\"9\n\x15GenerateImageResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\"!\n\x0fGetImageRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"$\n\x10GetImageResponse\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\"\x13\n\x11ListImagesRequest\",\n\x12ListImagesResponse\x12\x16\n\x06images\x18\x01 \x03(\tR\x06images\"$\n\x12\x44\x65leteImageRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x15\n\x13\x44\x65leteImageResponse2\xd2\x02\n\x0eTxt2ImgService\x12V\n\rGenerateImage\x12 .txt2img.v1.GenerateImageRequest\x1a!.txt2img.v1.GenerateImageResponse\"\x00\x12G\n\x08GetImage\x12\x1b.txt2img.v1.GetImageRequest\x1a\x1c.txt2img.v1.GetImageResponse\"\x00\x12M\n\nListImages\x12\x1d.txt2img.v1.ListImagesRequest\x1a\x1e.txt2img.v1.ListImagesResponse\"\x00\x12P\n\x0b\x44\x65leteImage\x12\x1e.txt2img.v1.DeleteImageRequest\x1a\x1f.txt2img.v1.DeleteImageResponse\"\x00\x42YZWgithub.com/eddiezane/open-source-summit-eu-2022-api-codegen/protos/txt2img/v1;txt2imgv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'txt2img.v1.txt2img_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZWgithub.com/eddiezane/open-source-summit-eu-2022-api-codegen/protos/txt2img/v1;txt2imgv1'
  _GENERATEIMAGEREQUEST._serialized_start=40
  _GENERATEIMAGEREQUEST._serialized_end=86
  _GENERATEIMAGERESPONSE._serialized_start=88
  _GENERATEIMAGERESPONSE._serialized_end=145
  _GETIMAGEREQUEST._serialized_start=147
  _GETIMAGEREQUEST._serialized_end=180
  _GETIMAGERESPONSE._serialized_start=182
  _GETIMAGERESPONSE._serialized_end=218
  _LISTIMAGESREQUEST._serialized_start=220
  _LISTIMAGESREQUEST._serialized_end=239
  _LISTIMAGESRESPONSE._serialized_start=241
  _LISTIMAGESRESPONSE._serialized_end=285
  _DELETEIMAGEREQUEST._serialized_start=287
  _DELETEIMAGEREQUEST._serialized_end=323
  _DELETEIMAGERESPONSE._serialized_start=325
  _DELETEIMAGERESPONSE._serialized_end=346
  _TXT2IMGSERVICE._serialized_start=349
  _TXT2IMGSERVICE._serialized_end=687
# @@protoc_insertion_point(module_scope)
